### ISSUE TITLE
  snapsource.includeProjectTree false is being ignored

### ISSUE THREAD

**Issue by teneon** [LeonKohli/snapsource#1]
Hi there,

amazing plugin! Good work! :+1: 

My IDE is "Cursor IDE" latest version, which is based on VSCode.
I am trying to play with available settings now.

I have successfully added:
"snapsource.excludePatterns": ["vault_*.yml"]
and it works as expected! When copy pasting the whole dir, vault_main.yml file inside that dir gets ignored! Great!

I tried to diable Include Project Tree by uncheck-ing the checkbox in Settings / extensions / snapsource ,but that didn't work. I tried to reload window, didn't help neither. I tried adding
` "snapsource.includeProjectTree": false`
into: ~/.config/Cursor/User/settings.json

```
{
// ...other settings...
  "workbench.settings.applyToAllProfiles": [],
  "snapsource.excludePatterns": [
    ".vscode",
    "vault_*.yml",
    "debug_*.yml",
    "*.log"
  ],
  "snapsource.includeProjectTree": false
}
```

But it is still always including project tree in the output. Any clues?

best regards,
Jim

**Comment by archneon** [comment]
Just to update you, after a while tree disappeared as i have specified it in config. So it's ok now, but it has some delay (a day or two), perhaps restart was neccessary, not sure why :)

**Comment by LeonKohli** [comment]
> Just to update you, after a while tree disappeared as i have specified it in config. So it's ok now, but it has some delay (a day or two), perhaps restart was neccessary, not sure why :)

You mean the update had some delay or disabling the tree setting itself?

**Comment by archneon** [comment]
@LeonKohli 
"snapsource.includeProjectTree": false
this option started to work with some delay, but now i think i know why. It's because you have updated Snapsource to fix this error and i guess extention automatically updated and then it started to work :) Thanks! It's amazing an extension, very useful!
